platform :ios, 9.0
use_frameworks!

target 'Dota2Helper' do

   # UI
   pod 'MJRefresh'
   pod 'SDCycleScrollView'
   pod 'SnapKit'

   # Network
   pod 'Kingfisher’
   pod 'ReachabilitySwift'
   pod 'Alamofire'

   # Debug
   pod 'Bugtags'
   pod ‘tingyunApp’

end