source 'https://git.coding.net/hging/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Dota2Helper' do
   pod 'Bugtags'
   pod 'Kingfisher’, ‘~> 3.0.1’
   pod 'MJRefresh', '~> 3.1.12'
   pod 'ReachabilitySwift'
   pod 'SDCycleScrollView','~> 1.65’
end